export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY'
export const SET_TARGET_CURRENCY = 'SET_TARGET_CURRENCY'
export const SET_CURRENCY_QUOTATION = 'SET_ORIGIN_CURRENCY_VALUE'
export const EXCHANGE_CURRENCY = 'EXCHANGE_CURRENCY'
